### ISSUE TITLE
Make it simple to show output as diff OR add information about how to accomplish this to docs

### ISSUE THREAD

**Issue by nicomen** [oalders/App-perlimports#17]
It would be useful if you don't go all in to be able to do something like:

```for a in `ack -f --perl`; do t=`mktemp`; perlimports --ignore-modules Test::More,Makefile.PL,Data::Dumper::Concise -f $a > $t; diff -ru $a $t; rm $t; done```

On second hand, perhaps with version control a simple in-place-edit and then running a `git add -p` should suffice.

Either way I think it would be useful to add the information to the docs

**Comment by oalders** [comment]
Sure, I would be happy to accept a doc patch for this. I can see how it would be helpful to just add a reporting option about what changed, but doing a diff in temp folder seems like it gets everyone to the same place with a lot less work.
