### ISSUE TITLE
non-exporting modules get braces inappropriately

### ISSUE THREAD

**Issue by karenetheridge** [oalders/App-perlimports#24]
```
use LWP::UserAgent;
```

gets turned into:

```
use LWP::UserAgent ();
```

This is odd because LWP::UserAgent doesn't export anything - it's an OO module.
Maybe look to see if the module has an `import` sub (that isn't UNIVERSAL::import)?

**Comment by oalders** [comment]
This is something that has come up a couple of times. At $work we always add parens, unless there's a good reason not to. It serves as a sort of documentation that "there's nothing to see here" and it makes `use` statements without parens more obvious. It also makes clear that there will be no attempt to look for an `import()` in this class.

Those things aren't so meaningful for people who are intimately familiar with a module, but for everyone else it saves them from checking docs to see if this is an OO module or if someone has just decided to import implicitly whatever the module likes to export.

So far I've resisted changing this behaviour. This is loosely based on `goimports` which has a real lack of TIMTOWDI. Right now I feel like adding the parens makes it clear that importing is a no-op. To me that's useful information to have when I'm scanning a list of imports in code I didn't write. I'll leave this issue open for people to disagree with me. :)

**Comment by karenetheridge** [comment]
I guess the question then is why does it add parens to some modules and not all? There is definitely an inconsistency here.

**Comment by oalders** [comment]
> I guess the question then is why does it add parens to some modules and not all? There is definitely an inconsistency here.

In cases where it's not clear what is correct, `perlimports` will err on the side of caution and leave the code untouched. I have a plan in mind to get to even more coverage of modules, but there's enough creativity in the way various modules work that I don't want to make too many assumptions.

If you want to give me some cases that should have been dealt with, I'm happy to look at them to see what's going on.

**Comment by oalders** [comment]
The coverage is (I think) much better now. We can re-open tickets for specific modules that are being ignored, but shouldn't be.
